# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'current'
        path: '$(Agent.WorkFolder)/current-artifacts'
        project: '$(System.TeamProjectId)'
        pipeline: '$(System.DefinitionId)'

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy Azure App to development'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial (5678f06d-0313-4e3f-a700-ba0b0d6f1a22)'
        appType: 'webApp'
        WebAppName: 'DevOpsReraDemo'
        packageForLinux: '$(Agent.WorkFolder)/current-artifacts'
        enableCustomDeployment: true
        DeploymentType: 'webDeploy'
        deployToSlotOrASE: true
        ResourceGroupName: 'test_resource_group'
